import { describe, expect, it } from "vitest";
import { parseAndValidateModelJson } from "../../../src/lib/json-response.js";
import {
  binaryOrAutogeneratedModelLayer,
  cleanQuestionAnalysis,
  cleanQuestionAnalyses,
  EMPTY_SUMMARIZE_MODEL,
  emptyCommitModelLayer,
  MAX_SUMMARIZE_PARTS,
  oversizedSplitModelLayer,
  OVERSIZED_SPLIT_MODEL,
  PATH_FILTER_SKIP_MODEL,
  enforceSignalReasons,
  groupClassifyJsonSchema,
  groupHistoryJsonSchema,
  hasSubstantiveDeterministic,
  isEmptyCommitSummary,
  maxSignal,
  mergeTechnologies,
  modelJsonSchema,
  prepareQuestionsJsonSchema,
  prepareReasonsJsonSchema,
  prepareTechnologiesJsonSchema,
  projectProfileJsonSchema,
  reportHistoryJsonSchema,
  reportMergeJsonSchema,
  reportNewHistoryJsonSchema,
  cvBulletsJsonSchema,
  roleNarrativeJsonSchema,
  routineCheckJsonSchema,
  storyPrepareJsonSchema,
} from "../../../src/lib/model.js";
import { emptyDeterministic, sampleModel } from "../../helpers.js";

const validCommitJson = JSON.stringify({
  summary: "Added handler",
  changeTypes: ["feature"],
  technologies: ["TypeScript"],
  technicalSignal: "medium",
  architectureSignal: "low",
  securitySignal: "low",
  signalReasons: { technical: "new module", architecture: "", security: "" },
  questionsAnalysis: [],
  confidence: "medium",
});

describe("maxSignal", () => {
  it("returns the higher signal on the low < medium < high scale", () => {
    expect(maxSignal("low", "high")).toBe("high");
    expect(maxSignal("medium", "low")).toBe("medium");
    expect(maxSignal("high", "high")).toBe("high");
  });
});

describe("mergeTechnologies", () => {
  it("dedupes case-insensitively while preserving first casing", () => {
    expect(mergeTechnologies(["Node.js"], ["node.js"], ["TypeScript"])).toEqual([
      "Node.js",
      "TypeScript",
    ]);
  });

  it("skips empty strings", () => {
    expect(mergeTechnologies(["  ", "Go"], undefined)).toEqual(["Go"]);
  });
});

describe("hasSubstantiveDeterministic", () => {
  it("returns false when only excluded/noise paths remain", () => {
    expect(
      hasSubstantiveDeterministic(
        emptyDeterministic({
          excludedFiles: ["frontend/package-lock.json"],
        }),
      ),
    ).toBe(false);
  });

  it("returns true when substantive files or churn exist", () => {
    expect(hasSubstantiveDeterministic(emptyDeterministic({ linesAdded: 1 }))).toBe(true);
    expect(
      hasSubstantiveDeterministic(
        emptyDeterministic({
          changedFiles: { added: ["src/a.ts"], modified: [], deleted: [], renamed: [] },
        }),
      ),
    ).toBe(true);
  });
});

describe("emptyCommitModelLayer", () => {
  it("returns a low-signal empty layer with (none) provenance", () => {
    const layer = emptyCommitModelLayer();
    expect(layer.summary).toBe("");
    expect(layer.questionsAnalysis).toEqual([]);
    expect(layer.confidence).toBe("low");
    expect(layer.provenance?.model).toBe(EMPTY_SUMMARIZE_MODEL);
    expect(isEmptyCommitSummary(layer)).toBe(true);
  });
});

describe("binaryOrAutogeneratedModelLayer", () => {
  it("returns a descriptive low-signal layer with path-filter provenance", () => {
    const det = emptyDeterministic({
      changedFiles: { added: ["build/a.bin", "gen/b.out"], modified: [], deleted: [], renamed: [] },
    });
    const layer = binaryOrAutogeneratedModelLayer(det);
    expect(layer.summary).toContain("2 path(s)");
    expect(layer.summary).toContain("auto-generated");
    expect(layer.technicalSignal).toBe("low");
    expect(layer.provenance?.model).toBe(PATH_FILTER_SKIP_MODEL);
    expect(isEmptyCommitSummary(layer)).toBe(false);
  });
});

describe("oversizedSplitModelLayer", () => {
  it("records the part cap in summary and provenance", () => {
    const layer = oversizedSplitModelLayer(545);
    expect(layer.summary).toContain("545 evidence parts");
    expect(layer.summary).toContain(String(MAX_SUMMARIZE_PARTS));
    expect(layer.provenance?.model).toBe(OVERSIZED_SPLIT_MODEL);
    expect(isEmptyCommitSummary(layer)).toBe(false);
  });
});

describe("isEmptyCommitSummary", () => {
  it("returns false for null and substantive summaries", () => {
    expect(isEmptyCommitSummary(null)).toBe(false);
    expect(isEmptyCommitSummary(undefined)).toBe(false);
    expect(isEmptyCommitSummary(sampleModel({ summary: "Did work" }))).toBe(false);
  });

  it("returns true for empty-skip layers and blank summaries", () => {
    expect(isEmptyCommitSummary(emptyCommitModelLayer())).toBe(true);
    expect(isEmptyCommitSummary(sampleModel({ summary: "   " }))).toBe(true);
  });
});

describe("enforceSignalReasons", () => {
  it("demotes non-low signals without a reason to low", () => {
    const fixed = enforceSignalReasons(
      sampleModel({
        technicalSignal: "high",
        architectureSignal: "medium",
        signalReasons: { technical: "  ", architecture: "ok", security: "" },
      }),
    );
    expect(fixed.technicalSignal).toBe("low");
    expect(fixed.architectureSignal).toBe("medium");
  });
});

describe("cleanQuestionAnalysis", () => {
  it("drops entries without a question and trims fields", () => {
    expect(
      cleanQuestionAnalysis([
        { observation: "  obs ", missingPiece: "gap", question: " q? " },
        { observation: "x", missingPiece: "y", question: "" },
      ]),
    ).toEqual([{ observation: "obs", missingPiece: "gap", question: "q?" }]);
    expect(cleanQuestionAnalysis("not-array")).toEqual([]);
  });
});

describe("cleanQuestionAnalyses", () => {
  it("normalizes lineage refs and drops empty questions", () => {
    const cleaned = cleanQuestionAnalyses([
      {
        observation: [" obs "],
        missingPiece: [" gap "],
        question: [" q? "],
        threadId: " 1700000000000000 ",
        derivedFromThreadIds: ["a", ""],
        derivedFromReportSignalRefs: [
          { dimension: "technical", index: 0 },
          { dimension: "bogus", index: 0 },
          { dimension: "architecture", index: -1 },
        ],
        derivedFromPreparedSignalSlots: [0, 9, 2],
        sourceGroupIds: [1, Number.NaN],
        sourceCommits: ["abc"],
        sourceSummaries: ["sum", null, "  "],
        sourceGroupId: 1,
        groupThreadIndex: 0,
        threadIndex: 1,
        evidenceExcerpt: " excerpt ",
        whyAsked: " because ",
      },
      { observation: [], missingPiece: [], question: [] },
    ]);
    expect(cleaned).toHaveLength(1);
    expect(cleaned[0]).toMatchObject({
      threadId: "1700000000000000",
      derivedFromThreadIds: ["a"],
      derivedFromReportSignalRefs: [{ dimension: "technical", index: 0 }],
      derivedFromPreparedSignalSlots: [0, 2],
      sourceGroupIds: [1],
      sourceCommits: ["abc"],
      sourceGroupId: 1,
      groupThreadIndex: 0,
      threadIndex: 1,
      evidenceExcerpt: "excerpt",
      whyAsked: "because",
    });
    expect(cleanQuestionAnalyses(null)).toEqual([]);
  });
});

describe("json schemas", () => {
  it("modelJsonSchema validates commit output", () => {
    expect(parseAndValidateModelJson(validCommitJson, modelJsonSchema())).toMatchObject({
      summary: "Added handler",
    });
  });

  it("groupClassifyJsonSchema requires context tiers", () => {
    const parsed = parseAndValidateModelJson(
      JSON.stringify({
        changeTypes: ["feature"],
        technicalSignal: "medium",
        architectureSignal: "low",
        securitySignal: "low",
        signalReasons: { technical: "x", architecture: "", security: "" },
        questionsAnalyses: [],
        confidence: "medium",
        hiContext: ["Core"],
        mediumContext: [],
        lowContext: [],
      }),
      groupClassifyJsonSchema(),
    ) as { hiContext: string[] };
    expect(parsed.hiContext).toEqual(["Core"]);
  });

  it("groupHistoryJsonSchema accepts history string", () => {
    expect(
      parseAndValidateModelJson('{"history":"Did work."}', groupHistoryJsonSchema()),
    ).toEqual({ history: "Did work." });
  });

  it("reportMergeJsonSchema accepts merged arrays", () => {
    const parsed = parseAndValidateModelJson(
      JSON.stringify({
        changeTypes: ["feature"],
        signalReasons: { technical: ["t"], architecture: [], security: [] },
        questionsAnalyses: [],
        confidence: "medium",
        hiContext: [],
        mediumContext: [],
        lowContext: [],
      }),
      reportMergeJsonSchema(),
    );
    expect(parsed).toBeTruthy();
  });

  it("storyPrepareJsonSchema accepts preparedContext", () => {
    expect(
      parseAndValidateModelJson('{"preparedContext":"I led the migration."}', storyPrepareJsonSchema()),
    ).toEqual({ preparedContext: "I led the migration." });
  });

  it("projectProfileJsonSchema accepts profile fields", () => {
    expect(
      parseAndValidateModelJson(
        JSON.stringify({
          summary: "CLI",
          domains: ["tooling"],
          apparentStack: ["TypeScript"],
          keyThemes: ["git"],
        }),
        projectProfileJsonSchema(),
      ),
    ).toMatchObject({ summary: "CLI" });
  });

  it("roleNarrativeJsonSchema accepts narrative array", () => {
    expect(
      parseAndValidateModelJson('{"narrative":["Impact one","Impact two"]}', roleNarrativeJsonSchema()),
    ).toEqual({ narrative: ["Impact one", "Impact two"] });
  });

  it("cvBulletsJsonSchema accepts cvBullets array", () => {
    expect(
      parseAndValidateModelJson(
        '{"cvBullets":["Built API","Designed schema"]}',
        cvBulletsJsonSchema(),
      ),
    ).toEqual({ cvBullets: ["Built API", "Designed schema"] });
  });

  it("prepareTechnologiesJsonSchema accepts technologies array", () => {
    expect(
      parseAndValidateModelJson('{"technologies":["TypeScript"]}', prepareTechnologiesJsonSchema()),
    ).toEqual({ technologies: ["TypeScript"] });
  });

  it("prepareReasonsJsonSchema accepts four reasons", () => {
    expect(
      parseAndValidateModelJson(
        '{"signalReasons":["a","b","c","d"]}',
        prepareReasonsJsonSchema(),
      ),
    ).toEqual({ signalReasons: ["a", "b", "c", "d"] });
  });

  it("prepareQuestionsJsonSchema accepts questionsAnalyses and confidence", () => {
    expect(
      parseAndValidateModelJson(
        '{"questionsAnalyses":[{"observation":["o"],"missingPiece":["m"],"question":["q1"]}],"confidence":"medium"}',
        prepareQuestionsJsonSchema(),
      ),
    ).toMatchObject({ confidence: "medium" });
  });

  it("routineCheckJsonSchema accepts routine flag", () => {
    expect(
      parseAndValidateModelJson('{"routine": true, "reason": "deps only"}', routineCheckJsonSchema()),
    ).toMatchObject({ routine: true });
  });

  it("reportHistoryJsonSchema accepts history strings", () => {
    expect(
      parseAndValidateModelJson('{"history":["entry one"]}', reportHistoryJsonSchema()),
    ).toEqual({ history: ["entry one"] });
  });

  it("reportNewHistoryJsonSchema accepts needed + text only", () => {
    expect(
      parseAndValidateModelJson('{"needed": true, "text": "Added deploy scripts."}', reportNewHistoryJsonSchema()),
    ).toMatchObject({ needed: true });
  });

  it("modelJsonSchema rejects invalid enum values", () => {
    expect(() =>
      parseAndValidateModelJson(
        validCommitJson.replace('"medium"', '"extreme"'),
        modelJsonSchema(),
      ),
    ).toThrow(/invalid enum/i);
  });
});
