sonar.projectKey=vzakharchenko_dev-workgraph
sonar.organization=forge-sql-orm

sonar.projectBaseDir=dev-workgraph-cli
sonar.sources=src
sonar.tests=__test__
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=__test__/**,scripts/**
#sonar.cpd.exclusions=examples/**,static/**,__tests__/**,scripts/**,forge-sql-orm-extra/scripts/**,forge-sql-orm-cli/**,forge-sql-orm-extra/__tests__/**,forge-sql-orm-extra/src/core/ForgeSQLExt.ts,forge-sql-orm-extra/src/core/ForgeSQLORM.ts

sonar.issue.ignore.multicriteria=e1,e2,e3

sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S4036
sonar.issue.ignore.multicriteria.e1.resourceKey=src/**

sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S5443
sonar.issue.ignore.multicriteria.e2.resourceKey=__test__/**

sonar.issue.ignore.multicriteria.e3.ruleKey=javascript:S5443
sonar.issue.ignore.multicriteria.e3.resourceKey=__test__/**
