sonar.projectKey=vzakharchenko_dev-workgraph
sonar.organization=forge-sql-orm

sonar.javascript.lcov.reportPaths=dev-workgraph-cli/coverage/lcov.info

sonar.exclusions=dev-workgraph-cli/__test__/**,dev-workgraph-cli/scripts/**,scripts/**
#sonar.cpd.exclusions=examples/**,static/**,__tests__/**,scripts/**,forge-sql-orm-extra/scripts/**,forge-sql-orm-cli/**,forge-sql-orm-extra/__tests__/**,forge-sql-orm-extra/src/core/ForgeSQLExt.ts,forge-sql-orm-extra/src/core/ForgeSQLORM.ts

#sonar.issue.ignore.multicriteria=e1,e2,e3
#
#sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S2933
#sonar.issue.ignore.multicriteria.e1.resourceKey=forge-sql-orm-extra/src/rovo/Rovo.ts
#
#sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S7786
#sonar.issue.ignore.multicriteria.e2.resourceKey=**/*
#
#sonar.issue.ignore.multicriteria.e3.ruleKey=typescript:S7781
#sonar.issue.ignore.multicriteria.e3.resourceKey=**/*