import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {
  repoCommitsDir,
  repoGroupsDir,
  repoFinishDir,
  repoPreparedDir,
  repoProjectPath,
  repoReportsDir,
  repoSummariesDir,
} from "../../../src/lib/config.js";
import { finishJsonFileName, finishQuestionsJsonFileName, finishQuestionVersionLabel } from "../../../src/lib/finish-load.js";
import { createFinishQuestions, writeFinishQuestions } from "../../../src/lib/finish-questions.js";
import type {
  CommitEvidenceRecord,
  CommitRecord,
  CommitSummaryRecord,
  FinishRecord,
  GroupRecord,
  PreparedRecord,
  ProjectContext,
  ReportRecord,
} from "../../../src/lib/records.js";
import {
  emptyDeterministic,
  sampleCommit,
  sampleGroup,
  sampleGroupModel,
  sampleModel,
  sampleReport,
  sampleReportModel,
} from "../../helpers.js";

export const FAKE_REPO = "/tmp/workgraph-fake-repo";

export function setupWorkgraphHome(): { tmpHome: string; restore: () => void } {
  const tmpHome = fs.mkdtempSync(path.join(os.tmpdir(), "workgraph-actions-"));
  const previous = process.env.WORKGRAPH_HOME;
  process.env.WORKGRAPH_HOME = tmpHome;
  return {
    tmpHome,
    restore: () => {
      if (previous === undefined) delete process.env.WORKGRAPH_HOME;
      else process.env.WORKGRAPH_HOME = previous;
      fs.rmSync(tmpHome, { recursive: true, force: true });
      process.exitCode = undefined;
    },
  };
}

export function writeProjectContext(repoPath: string, period?: string): void {
  const ctx: ProjectContext = {
    role: "Senior Developer",
    profile: {
      summary: "CLI tool",
      domains: ["tooling"],
      apparentStack: ["TypeScript"],
      keyThemes: ["git"],
    },
    story: { raw: "Built a CLI.", preparedContext: "I built a CLI." },
    readme: { present: true, path: "README.md" },
    provenance: { model: "test-model", generatedAt: "2026-01-01T00:00:00Z" },
  };
  const file = repoProjectPath(repoPath, period);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(ctx));
}

export function seedCommit(
  repoPath: string,
  overrides: Partial<CommitRecord> & { commitHash: string },
  period?: string,
): { jsonPath: string; patchPath: string; summaryPath?: string } {
  const { model, ...rest } = overrides;
  const record = sampleCommit({ ...rest, model: null });
  const dir = path.join(repoCommitsDir(repoPath, period), String(record.timestamp));
  fs.mkdirSync(dir, { recursive: true });
  const jsonPath = path.join(dir, `${record.commitHash}.json`);
  const patchPath = path.join(dir, `${record.commitHash}.patch`);
  const evidence: CommitEvidenceRecord = {
    commitHash: record.commitHash,
    timestamp: record.timestamp,
    title: record.title,
    author: record.author,
    deterministic: record.deterministic,
  };
  fs.writeFileSync(jsonPath, `${JSON.stringify(evidence, null, 2)}\n`);
  fs.writeFileSync(patchPath, "diff --git a/src/a.ts\n+export const x = 1;\n");
  if (model) {
    const summaryPath = seedSummary(repoPath, record, model, period);
    return { jsonPath, patchPath, summaryPath };
  }
  return { jsonPath, patchPath };
}

/** Seeds a split evidence export (manifest + two parts). */
export function seedSplitCommit(
  repoPath: string,
  commitHash: string,
  period?: string,
): { manifestPath: string; partPaths: string[] } {
  const timestamp = 1_700_000_000;
  const dir = path.join(repoCommitsDir(repoPath, period), String(timestamp));
  fs.mkdirSync(dir, { recursive: true });

  const manifest: CommitEvidenceRecord = {
    commitHash,
    timestamp,
    title: "Large change",
    author: "dev@example.com",
    split: true,
    partCount: 2,
    deterministic: emptyDeterministic(),
  };
  const manifestPath = path.join(dir, `${commitHash}.json`);
  fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

  const partPaths: string[] = [];
  for (const part of [1, 2]) {
    const partJson = path.join(dir, `${commitHash}.part${part}.json`);
    const partPatch = path.join(dir, `${commitHash}.part${part}.patch`);
    fs.writeFileSync(
      partJson,
      `${JSON.stringify(
        {
          commitHash,
          timestamp,
          title: manifest.title,
          author: manifest.author,
          part,
          partCount: 2,
          patchTruncated: false,
          deterministic: emptyDeterministic(),
        },
        null,
        2,
      )}\n`,
    );
    fs.writeFileSync(
      partPatch,
      `diff --git a/src/part${part}.ts b/src/part${part}.ts\n+export const p${part} = ${part};\n`,
    );
    partPaths.push(partJson);
  }

  return { manifestPath, partPaths };
}

/** Seeds a split export with a binary/autogenerated bucket as the last part. */
export function seedSplitCommitWithBucket(
  repoPath: string,
  commitHash: string,
  period?: string,
): { manifestPath: string; partPaths: string[] } {
  const timestamp = 1_700_000_000;
  const dir = path.join(repoCommitsDir(repoPath, period), String(timestamp));
  fs.mkdirSync(dir, { recursive: true });

  const manifest: CommitEvidenceRecord = {
    commitHash,
    timestamp,
    title: "Large change",
    author: "dev@example.com",
    split: true,
    partCount: 3,
    pathFilterApplied: true,
    deterministic: emptyDeterministic(),
  };
  const manifestPath = path.join(dir, `${commitHash}.json`);
  fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

  const partPaths: string[] = [];
  for (const part of [1, 2]) {
    const partJson = path.join(dir, `${commitHash}.part${part}.json`);
    const partPatch = path.join(dir, `${commitHash}.part${part}.patch`);
    fs.writeFileSync(
      partJson,
      `${JSON.stringify(
        {
          commitHash,
          timestamp,
          title: manifest.title,
          author: manifest.author,
          part,
          partCount: 3,
          patchTruncated: false,
          deterministic: emptyDeterministic(),
        },
        null,
        2,
      )}\n`,
    );
    fs.writeFileSync(
      partPatch,
      `diff --git a/src/part${part}.ts b/src/part${part}.ts\n+export const p${part} = ${part};\n`,
    );
    partPaths.push(partJson);
  }

  const bucketJson = path.join(dir, `${commitHash}.part3.json`);
  const bucketPatch = path.join(dir, `${commitHash}.part3.patch`);
  fs.writeFileSync(
    bucketJson,
    `${JSON.stringify(
      {
        commitHash,
        timestamp,
        title: manifest.title,
        author: manifest.author,
        part: 3,
        partCount: 3,
        patchTruncated: false,
        isBinaryOrAutogenerated: true,
        deterministic: {
          ...emptyDeterministic(),
          changedFiles: {
            added: ["build/out.bin"],
            modified: [],
            deleted: [],
            renamed: [],
          },
        },
      },
      null,
      2,
    )}\n`,
  );
  fs.writeFileSync(bucketPatch, "commit abc\n\n# build/out.bin\n");
  partPaths.push(bucketJson);

  return { manifestPath, partPaths };
}

export function seedSummary(
  repoPath: string,
  commit: Pick<CommitRecord, "commitHash" | "timestamp">,
  model: NonNullable<CommitRecord["model"]>,
  period?: string,
): string {
  const summary: CommitSummaryRecord = {
    commitHash: commit.commitHash,
    timestamp: commit.timestamp,
    sourceEvidence: String(commit.timestamp),
    model,
  };
  const summaryPath = path.join(
    repoSummariesDir(repoPath, period),
    String(commit.timestamp),
    `${commit.commitHash}.json`,
  );
  fs.mkdirSync(path.dirname(summaryPath), { recursive: true });
  fs.writeFileSync(summaryPath, `${JSON.stringify(summary, null, 2)}\n`);
  return summaryPath;
}

export function seedGroup(
  repoPath: string,
  overrides: Partial<GroupRecord> = {},
  period?: string,
): string {
  const record = sampleGroup(overrides);
  const groupsDir = repoGroupsDir(repoPath, period);
  fs.mkdirSync(groupsDir, { recursive: true });
  const file = path.join(groupsDir, `${record.timestampEnd}.json`);
  fs.writeFileSync(file, `${JSON.stringify(record, null, 2)}\n`);
  return file;
}

export function seedReport(
  repoPath: string,
  overrides: Partial<ReportRecord> = {},
  period?: string,
): string {
  const record = sampleReport(overrides);
  const reportsDir = repoReportsDir(repoPath, period);
  fs.mkdirSync(reportsDir, { recursive: true });
  const file = path.join(reportsDir, `${record.reportId}.json`);
  fs.writeFileSync(file, `${JSON.stringify(record, null, 2)}\n`);
  return file;
}

export function seedPrepared(repoPath: string, reportFile: string, period?: string): string {
  const preparedId = 1_700_000_000;
  const questionAnalyses = [
    { observation: ["o1"], missingPiece: ["m1"], question: ["Was it production?"] },
    { observation: ["o2"], missingPiece: ["m2"], question: ["Who designed it?"] },
    { observation: ["o3"], missingPiece: ["m3"], question: ["Any security impact?"] },
    { observation: ["o4"], missingPiece: ["m4"], question: ["Customer driven?"] },
  ];
  const record: PreparedRecord = {
    preparedId,
    sourceReport: reportFile,
    groupCount: 1,
    model: {
      changeTypes: ["feature"],
      technologies: ["TypeScript"],
      technicalSignal: "medium",
      architectureSignal: "low",
      securitySignal: "low",
      signalReasons: ["Reason one", "Reason two", "Reason three", "Reason four"],
      confidence: "medium",
      history: "I implemented the feature.",
      provenance: {
        model: "test-model",
        generatedAt: "2026-01-01T00:00:00Z",
        sourceReport: reportFile,
      },
    },
  };
  const dir = repoPreparedDir(repoPath, period);
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, `${record.preparedId}.json`);
  fs.writeFileSync(file, `${JSON.stringify(record, null, 2)}\n`);

  const finishDir = repoFinishDir(repoPath, period);
  fs.mkdirSync(finishDir, { recursive: true });
  writeFinishQuestions(
    path.join(finishDir, finishQuestionsJsonFileName(preparedId, 1)),
    createFinishQuestions(
      questionAnalyses.map((thread) => thread.question[0]!),
      {
        sourceFinal: finishJsonFileName(preparedId, 1),
        sourceReport: reportFile,
      },
      1_700_000_000_000,
      questionAnalyses,
    ),
  );
  return file;
}

export function seedFinish(
  repoPath: string,
  preparedFile: string,
  overrides: Partial<FinishRecord> = {},
  period?: string,
  version = 1,
): string {
  const finishId = overrides.finishId ?? 1_700_000_000;
  const defaultQuestions = [
    "Was it production?",
    "Who designed it?",
    "Any security impact?",
    "Customer driven?",
  ];
  const defaultAnswers = ["Staging only.", "I did.", "No.", "Internal."];
  const legacyAnswers = overrides.answers as { question: string; answer: string }[] | undefined;
  const questionTexts = legacyAnswers?.map((a) => a.question) ?? defaultQuestions;
  const jsonFile = finishJsonFileName(finishId, version);
  const questionsFile = finishQuestionsJsonFileName(finishId, version);
  const questionsRecord = createFinishQuestions(
    questionTexts,
    { sourceFinal: jsonFile, sourceReport: "1700000000.json" },
    1_700_000_000_000,
  );
  const dir = repoFinishDir(repoPath, period);
  fs.mkdirSync(dir, { recursive: true });
  writeFinishQuestions(path.join(dir, questionsFile), questionsRecord);
  const answers =
    legacyAnswers?.map((entry, i) => ({
      questionId: questionsRecord.questions[i]?.id ?? questionsRecord.questions[0]!.id,
      answer: entry.answer,
    })) ??
    questionsRecord.questions.map((q, i) => ({
      questionId: q.id,
      answer: defaultAnswers[i] ?? "",
    }));
  const record: FinishRecord = {
    finishId,
    sourcePrepared: preparedFile,
    sourceReport: "1700000000.json",
    sourceQuestions: {
      [finishId]: Array.from({ length: version }, (_, i) => finishQuestionVersionLabel(i + 1)),
    },
    round: version,
    version,
    project: path.basename(repoPath),
    role: "Senior Developer",
    technologies: ["TypeScript"],
    history: "I implemented the feature in staging.",
    narrative: ["Bullet one", "Bullet two", "Bullet three", "Bullet four"],
    cvBullets: [
      "Built CLI tooling for git history reconstruction.",
      "Designed LLM pipeline stages for commit summarization.",
      "Implemented token usage tracking across pipeline steps.",
      "Refactored report merge for append-only resume semantics.",
    ],
    answers,
    outputMarkdown: version <= 1 ? `${finishId}.md` : `${finishId}.v${version}.md`,
    provenance: { model: "test-model", generatedAt: "2026-01-01T00:00:00Z" },
    ...overrides,
    answers,
  };
  const file = path.join(dir, jsonFile);
  fs.writeFileSync(file, `${JSON.stringify(record, null, 2)}\n`);
  fs.writeFileSync(
    path.join(dir, record.outputMarkdown),
    "# finish\n",
  );
  return file;
}

export const sampleGitCommit = {
  hash: "abc1234567890abc1234567890abc1234567890",
  timestamp: 1_700_000_000,
  email: "dev@example.com",
  name: "Dev",
  subject: "Add feature",
};

export function modelLayerPayload() {
  return {
    summary: "Changed src/a.ts",
    changeTypes: ["feature"],
    technologies: ["TypeScript"],
    technicalSignal: "medium",
    architectureSignal: "low",
    securitySignal: "low",
    signalReasons: { technical: "logic change", architecture: "", security: "" },
    questionsAnalysis: [],
    confidence: "medium",
  };
}

export function groupClassifyPayload() {
  return {
    ...modelLayerPayload(),
    questionsAnalyses: [],
    hiContext: ["Core feature"],
    mediumContext: [],
    lowContext: [],
  };
}

export function chatJsonFromSchema(schema: Record<string, unknown>): unknown {
  const required = (schema.required as string[] | undefined) ?? [];
  if (required.includes("preparedContext")) return { preparedContext: "Prepared story." };
  if (required.includes("summary") && required.includes("changeTypes")) {
    return modelLayerPayload();
  }
  if (required.includes("summary") && required.length === 1) {
    return { summary: "Final commit summary." };
  }
  if (
    required.includes("signalReasons") &&
    !required.includes("changeTypes") &&
    (schema.properties as Record<string, Record<string, unknown>>)?.signalReasons?.type ===
      "object"
  ) {
    return {
      signalReasons: {
        technical: "Polished technical reason.",
        architecture: "",
        security: "",
      },
    };
  }
  if (required.includes("questionsAnalysis") && !required.includes("summary")) {
    return {
      questionsAnalysis: [
        {
          observation: "Shows feature work.",
          missingPiece: "Production scope unknown.",
          question: "Did this ship to production?",
        },
        {
          observation: "Touches auth module.",
          missingPiece: "Ownership unclear.",
          question: "Did you design the auth flow?",
        },
        {
          observation: "Adds tests.",
          missingPiece: "Coverage intent unknown.",
          question: "Were these tests required by review?",
        },
        {
          observation: "Config changes present.",
          missingPiece: "Environment unknown.",
          question: "Which environment does this target?",
        },
      ],
    };
  }
  if (required.includes("summary") && required.includes("domains")) {
    return {
      summary: "CLI",
      domains: ["tooling"],
      apparentStack: ["TypeScript"],
      keyThemes: ["git"],
    };
  }
  if (required.includes("routine")) return { routine: false, reason: "feature work" };
  if (required.includes("needed")) return { needed: true, text: "Added new capability." };
  const historyProp = (schema.properties as Record<string, Record<string, unknown>> | undefined)
    ?.history;
  if (required.includes("history") && historyProp?.type === "array") {
    return { history: ["Condensed history entry."] };
  }
  if (required.includes("history") && historyProp?.type === "string") {
    return { history: "Session history narrative." };
  }
  if (required.includes("hiContext")) return groupClassifyPayload();
  if (
    required.includes("signalReasons") &&
    (schema.properties as Record<string, Record<string, unknown>>)?.signalReasons?.type ===
      "array"
  ) {
    return { signalReasons: ["r1", "r2", "r3", "r4"] };
  }
  if (required.includes("evidenceExcerpts")) {
    const props = (schema.properties as Record<string, Record<string, unknown>> | undefined)
      ?.evidenceExcerpts;
    const count = typeof props?.maxItems === "number" ? props.maxItems : 4;
    return {
      evidenceExcerpts: Array.from(
        { length: count },
        (_, i) => `- Scoped evidence ${i + 1}.\nRelated commits: abc12345`,
      ),
    };
  }
  if (required.includes("lineage")) {
    return {
      lineage: [
        {
          derivedFromThreadIds: ["1700000100000000"],
          derivedFromReportSignalRefs: [{ dimension: "technical", index: 0 }],
          derivedFromPreparedSignalSlots: [0],
        },
      ],
    };
  }
  if (required.includes("questionsAnalyses") && required.includes("confidence")) {
    return {
      questionsAnalyses: [
        { observation: ["o1"], missingPiece: ["m1"], question: ["q1"] },
        { observation: ["o2"], missingPiece: ["m2"], question: ["q2"] },
        { observation: ["o3"], missingPiece: ["m3"], question: ["q3"] },
        { observation: ["o4"], missingPiece: ["m4"], question: ["q4"] },
      ],
      confidence: "medium",
    };
  }
  if (required.includes("technologies") && !required.includes("summary")) {
    return { technologies: ["TypeScript"] };
  }
  if (required.includes("changeTypes") && required.includes("hiContext")) {
    return {
      changeTypes: ["feature"],
      signalReasons: { technical: ["t"], architecture: [], security: [] },
      questionsAnalyses: [],
      confidence: "medium",
      hiContext: ["Core"],
      mediumContext: [],
      lowContext: [],
    };
  }
  if (required.includes("narrative")) {
    return { narrative: ["Bullet one", "Bullet two", "Bullet three", "Bullet four"] };
  }
  if (required.includes("cvBullets")) {
    return {
      cvBullets: [
        "Built CLI tooling for git history reconstruction.",
        "Designed LLM pipeline stages for commit summarization.",
        "Implemented token usage tracking across pipeline steps.",
        "Refactored report merge for append-only resume semantics.",
      ],
    };
  }
  return modelLayerPayload();
}

export function summarizedCommit(hash: string): CommitRecord {
  return sampleCommit({
    commitHash: hash,
    timestamp: 1_700_000_000,
    model: sampleModel({ summary: "Did work", technicalSignal: "high" }),
  });
}

export function summarizedGroup(overrides: Partial<GroupRecord> = {}): GroupRecord {
  return sampleGroup({
    timestampEnd: 1_700_000_000,
    model: sampleGroupModel({ history: "Built the scheduler." }),
    ...overrides,
  });
}

export function sampleReportRecord(): ReportRecord {
  return sampleReport({
    reportId: 1_700_000_000,
    deterministic: { ...emptyDeterministic(), historySource: [["1700000000.json"]] },
    model: sampleReportModel({
      hiContext: ["Existing work"],
      signalReasons: { technical: ["reason"], architecture: [], security: [] },
    }),
    history: [{ text: "Existing history" }],
  });
}
