// SPDX-FileCopyrightText: 2026 Vasyl Zakharchenko
// SPDX-License-Identifier: Apache-2.0

import type { DeterministicLayer } from "./records.js";

/** Provenance `model` when summarize skips the LLM (empty / noise-only patch). */
export const EMPTY_SUMMARIZE_MODEL = "(none)";

/** Provenance `model` when summarize skips the LLM (binary/autogenerated bucket part). */
export const PATH_FILTER_SKIP_MODEL = "(path-filter)";

/** Provenance `model` when summarize skips per-part LLM (split exceeds {@link MAX_SUMMARIZE_PARTS}). */
export const OVERSIZED_SPLIT_MODEL = "(oversized-split)";

/** Maximum split evidence parts summarized with per-part LLM calls. */
export const MAX_SUMMARIZE_PARTS = 20;

/** Allowed coarse signal levels. No numeric scores (MVP §2). */
const SIGNALS = ["low", "medium", "high"] as const;
export type Signal = (typeof SIGNALS)[number];

/** Returns the higher of two signal levels on the low < medium < high scale. */
export function maxSignal(a: Signal, b: Signal): Signal {
  return SIGNALS.indexOf(a) >= SIGNALS.indexOf(b) ? a : b;
}

/** Allowed change-type tags (MVP §2). */
const CHANGE_TYPES = [
  "feature",
  "bugfix",
  "refactoring",
  "security",
  "infrastructure",
  "testing",
  "configuration",
  "developer-tooling",
  "architecture",
  "documentation",
  "deployment",
] as const;

/**
 * One reasoned open question on a single commit: what the diff shows, the human
 * context the diff cannot establish, and the question to recover it. All three
 * fields are English prose.
 */
export interface QuestionAnalysis {
  /** What the diff actually shows (grounded in the patch, not the commit message). */
  observation: string;
  /** The human context the patch cannot establish (ownership, intent, production use, …). */
  missingPiece: string;
  /** The single question to ask the human to recover that missing context. */
  question: string;
}

/**
 * Reference into report `signalReasons[dimension][index]` (LLM output at prepare/deepen).
 */
interface ReportSignalReasonRef {
  dimension: "technical" | "architecture" | "security";
  index: number;
}

/**
 * The aggregated form of {@link QuestionAnalysis} used at group and report level.
 * Because a group/report merges several commits, each field is an ARRAY: the
 * merged observations, the merged missing pieces, and the merged questions that
 * belong to one coherent open thread.
 */
export interface QuestionAnalyses {
  observation: string[];
  missingPiece: string[];
  question: string[];
  /** Stable opaque id for tracing threads through report/prepare merges. */
  threadId?: string;
  /** Commit hashes parallel to `observation` (CLI-attached, not from the model). */
  sourceCommits?: string[];
  /** Summary paths parallel to `observation`. */
  sourceSummaries?: (string | null)[];
  /** Primary work-session group id (`GroupRecord.groupId`). */
  sourceGroupId?: number;
  /** All group ids that contributed (report-level union). */
  sourceGroupIds?: number[];
  /** Index of this thread within the group's `questionsAnalyses`. */
  groupThreadIndex?: number;
  /** Parent thread ids when this entry was merged from prior stages. */
  derivedFromThreadIds?: string[];
  /** Report signal-reason catalog refs from prepare/deepen LLM (resolved code-side). */
  derivedFromReportSignalRefs?: ReportSignalReasonRef[];
  /** Prepared collapsed signal slots 0..3 from prepare/deepen LLM (resolved code-side). */
  derivedFromPreparedSignalSlots?: number[];
  /** Index 0..3 after `prepare` reframing. */
  threadIndex?: number;
  /** How this thread traces back after prepare (schema ≥ 1.0.5). */
  lineageKind?: "report-thread" | "signal-reason";
  /** Index into prepared `signalReasons` when {@link lineageKind} is `signal-reason`. */
  derivedFromSignalReasonIndex?: number;
  /** Compact human-readable source shown before Q&A (often code-built). */
  evidenceExcerpt?: string;
  /** Why this question matters for the developer's role. */
  whyAsked?: string;
}

/**
 * The model-generated interpretation layer of a commit record.
 * This is interpretation, not evidence — it may be wrong.
 */
export interface ModelLayer {
  summary: string;
  changeTypes: string[];
  /** Languages, frameworks, tools, and libraries the patch actually uses. */
  technologies: string[];
  technicalSignal: Signal;
  architectureSignal: Signal;
  securitySignal: Signal;
  signalReasons: {
    technical: string;
    architecture: string;
    security: string;
  };
  /** Reasoned open questions: observation → missing piece → question (English). */
  questionsAnalysis: QuestionAnalysis[];
  confidence: Signal;
  /** Provenance attached by the CLI after generation (not produced by the model). */
  provenance?: {
    model: string;
    generatedAt: string;
  };
}

/**
 * True when the deterministic layer lists no substantive file changes
 * (e.g. only noise/excluded paths remained after evidence export).
 * @param det - The commit deterministic layer.
 */
export function hasSubstantiveDeterministic(det: DeterministicLayer): boolean {
  const cf = det.changedFiles;
  if (
    cf.added.length > 0 ||
    cf.modified.length > 0 ||
    cf.deleted.length > 0 ||
    cf.renamed.length > 0
  ) {
    return true;
  }
  return det.linesAdded > 0 || det.linesDeleted > 0;
}

/**
 * Default model layer for commits whose patch has no substantive diff content.
 * {@link EMPTY_SUMMARIZE_MODEL} is recorded in provenance — no LLM was used.
 */
export function emptyCommitModelLayer(): ModelLayer {
  return {
    summary: "",
    changeTypes: [],
    technologies: [],
    technicalSignal: "low",
    architectureSignal: "low",
    securitySignal: "low",
    signalReasons: { technical: "", architecture: "", security: "" },
    questionsAnalysis: [],
    confidence: "low",
    provenance: {
      model: EMPTY_SUMMARIZE_MODEL,
      generatedAt: new Date().toISOString(),
    },
  };
}

/**
 * Predefined model layer for a binary/autogenerated evidence bucket part.
 * {@link PATH_FILTER_SKIP_MODEL} is recorded in provenance — no summarize LLM was used.
 * @param det - Scoped deterministic layer for the bucket part.
 */
export function binaryOrAutogeneratedModelLayer(det: DeterministicLayer): ModelLayer {
  const cf = det.changedFiles;
  const pathCount = cf.added.length + cf.modified.length + cf.deleted.length + cf.renamed.length;
  const summary =
    pathCount > 0
      ? `${pathCount} path(s) classified as likely binary or auto-generated by filename; diff content was not analyzed as authored code.`
      : "Paths classified as likely binary or auto-generated by filename; diff content was not analyzed as authored code.";

  return {
    summary,
    changeTypes: [],
    technologies: [],
    technicalSignal: "low",
    architectureSignal: "low",
    securitySignal: "low",
    signalReasons: { technical: "", architecture: "", security: "" },
    questionsAnalysis: [],
    confidence: "low",
    provenance: {
      model: PATH_FILTER_SKIP_MODEL,
      generatedAt: new Date().toISOString(),
    },
  };
}

/**
 * Predefined model layer for split commits with too many evidence parts for per-part LLM analysis.
 * {@link OVERSIZED_SPLIT_MODEL} is recorded in provenance — no summarize LLM was used.
 * @param partCount - Total evidence parts on the commit manifest.
 */
export function oversizedSplitModelLayer(partCount: number): ModelLayer {
  return {
    summary: `Commit split into ${partCount} evidence parts; per-part LLM analysis skipped (cap ${MAX_SUMMARIZE_PARTS}).`,
    changeTypes: [],
    technologies: [],
    technicalSignal: "low",
    architectureSignal: "low",
    securitySignal: "low",
    signalReasons: { technical: "", architecture: "", security: "" },
    questionsAnalysis: [],
    confidence: "low",
    provenance: {
      model: OVERSIZED_SPLIT_MODEL,
      generatedAt: new Date().toISOString(),
    },
  };
}

/**
 * True when summarize produced an empty summary (noise-only / empty patch skip).
 * Unsummarized commits (`model` null/undefined) are not empty.
 * @param model - The commit model layer, if any.
 */
export function isEmptyCommitSummary(model: ModelLayer | null | undefined): boolean {
  if (!model) return false;
  if (model.provenance?.model === EMPTY_SUMMARIZE_MODEL) return true;
  return !model.summary.trim();
}

/**
 * JSON Schema passed to Ollama's `format` parameter to force a structured,
 * schema-valid response. Mirrors {@link ModelLayer} minus provenance.
 */
export function modelJsonSchema(): Record<string, unknown> {
  const signal = { type: "string", enum: [...SIGNALS] };
  return {
    type: "object",
    properties: {
      summary: { type: "string" },
      changeTypes: { type: "array", items: { type: "string", enum: [...CHANGE_TYPES] } },
      technologies: { type: "array", items: { type: "string" } },
      technicalSignal: signal,
      architectureSignal: signal,
      securitySignal: signal,
      signalReasons: {
        type: "object",
        properties: {
          technical: { type: "string" },
          architecture: { type: "string" },
          security: { type: "string" },
        },
        required: ["technical", "architecture", "security"],
      },
      questionsAnalysis: {
        type: "array",
        items: {
          type: "object",
          properties: {
            observation: { type: "string" },
            missingPiece: { type: "string" },
            question: { type: "string" },
          },
          required: ["observation", "missingPiece", "question"],
        },
      },
      confidence: signal,
    },
    required: [
      "summary",
      "changeTypes",
      "technologies",
      "technicalSignal",
      "architectureSignal",
      "securitySignal",
      "signalReasons",
      "questionsAnalysis",
      "confidence",
    ],
  };
}

/**
 * JSON Schema for the group CLASSIFY session: session-level signals + change
 * types + questionsAnalyses, plus three tiers of **context bullets** (strings, merged
 * by meaning). No `summary` — that is produced separately by the compose step.
 */
export function groupClassifyJsonSchema(): Record<string, unknown> {
  const base = modelJsonSchema();
  const props = { ...(base.properties as Record<string, unknown>) };
  // `summary` is produced by the compose step; `technologies` is a deterministic
  // union of the member commits; the per-commit `questionsAnalysis` is replaced by
  // the aggregated `questionsAnalyses` below — none of these is re-derived here.
  delete props.summary;
  delete props.technologies;
  delete props.questionsAnalysis;
  delete props.questions;
  const strArray = { type: "array", items: { type: "string" } };
  const required = (base.required as string[]).filter(
    (field) =>
      field !== "summary" &&
      field !== "technologies" &&
      field !== "questionsAnalysis" &&
      field !== "questions",
  );
  return {
    type: "object",
    properties: {
      ...props,
      questionsAnalyses: aggregatedQuestionAnalysisSchema(),
      hiContext: strArray,
      mediumContext: strArray,
      lowContext: strArray,
    },
    required: [...required, "questionsAnalyses", "hiContext", "mediumContext", "lowContext"],
  };
}

/** JSON Schema for the aggregated `questionsAnalyses` (group/report): array-valued fields. */
function aggregatedQuestionAnalysisSchema(opts?: {
  allowDerivedFrom?: boolean;
  allowQuestionCards?: boolean;
}): Record<string, unknown> {
  const strArray = { type: "array", items: { type: "string" } };
  const properties: Record<string, unknown> = {
    observation: strArray,
    missingPiece: strArray,
    question: strArray,
  };
  if (opts?.allowDerivedFrom) {
    properties.derivedFromThreadIds = strArray;
    properties.derivedFromReportSignalRefs = {
      type: "array",
      items: {
        type: "object",
        properties: {
          dimension: { type: "string", enum: ["technical", "architecture", "security"] },
          index: { type: "integer", minimum: 0 },
        },
        required: ["dimension", "index"],
      },
    };
    properties.derivedFromPreparedSignalSlots = {
      type: "array",
      items: { type: "integer", minimum: 0, maximum: 3 },
    };
  }
  if (opts?.allowQuestionCards) {
    properties.whyAsked = { type: "string" };
    properties.evidenceExcerpt = { type: "string" };
  }
  return {
    type: "array",
    items: {
      type: "object",
      properties,
      required: ["observation", "missingPiece", "question"],
    },
  };
}

/**
 * JSON Schema for the group COMPOSE session: a single merged HISTORY (a fuller
 * account) built from the classified tiers and the member commits' summaries.
 */
export function groupHistoryJsonSchema(): Record<string, unknown> {
  return {
    type: "object",
    properties: { history: { type: "string" } },
    required: ["history"],
  };
}

/**
 * JSON Schema for the report MERGE session: combines two model layers. Signal
 * *levels* are computed in code (max), so the model only returns `signalReasons`
 * as arrays plus the merged change types, questionsAnalyses, confidence, and
 * re-ranked context tiers.
 */
export function reportMergeJsonSchema(): Record<string, unknown> {
  const strArray = { type: "array", items: { type: "string" } };
  return {
    type: "object",
    properties: {
      changeTypes: { type: "array", items: { type: "string", enum: [...CHANGE_TYPES] } },
      signalReasons: {
        type: "object",
        properties: { technical: strArray, architecture: strArray, security: strArray },
        required: ["technical", "architecture", "security"],
      },
      questionsAnalyses: aggregatedQuestionAnalysisSchema(),
      confidence: { type: "string", enum: [...SIGNALS] },
      hiContext: strArray,
      mediumContext: strArray,
      lowContext: strArray,
    },
    required: [
      "changeTypes",
      "signalReasons",
      "questionsAnalyses",
      "confidence",
      "hiContext",
      "mediumContext",
      "lowContext",
    ],
  };
}

/** JSON Schema for `init` session 1: the role-adjusted prepared story context. */
export function storyPrepareJsonSchema(): Record<string, unknown> {
  return {
    type: "object",
    properties: { preparedContext: { type: "string" } },
    required: ["preparedContext"],
  };
}

/** JSON Schema for `init` session 2: the structured project profile. */
export function projectProfileJsonSchema(): Record<string, unknown> {
  const strArray = { type: "array", items: { type: "string" } };
  return {
    type: "object",
    properties: {
      summary: { type: "string" },
      domains: strArray,
      apparentStack: strArray,
      keyThemes: strArray,
    },
    required: ["summary", "domains", "apparentStack", "keyThemes"],
  };
}

/** JSON Schema for `evidence` path filter: binary vs auto-generated file signatures. */
export function pathClassificationJsonSchema(): Record<string, unknown> {
  return {
    type: "object",
    properties: {
      likelyBinary: { type: "array", items: { type: "string" } },
      likelyGenerated: { type: "array", items: { type: "string" } },
    },
    required: ["likelyBinary", "likelyGenerated"],
    additionalProperties: false,
  };
}

/** JSON Schema for `final`: the Role Narrative — four impact bullet points. */
export function roleNarrativeJsonSchema(): Record<string, unknown> {
  return {
    type: "object",
    properties: { narrative: { type: "array", items: { type: "string" } } },
    required: ["narrative"],
  };
}

/** JSON Schema for `final`: four impersonal CV/resume bullet points. */
export function cvBulletsJsonSchema(): Record<string, unknown> {
  return {
    type: "object",
    properties: { cvBullets: { type: "array", items: { type: "string" } } },
    required: ["cvBullets"],
  };
}

/**
 * Case-insensitively unions technology lists, preserving the first-seen casing
 * and order. Used to accumulate `technologies` across commits → groups → report
 * (deterministic, no model). The model only cleans/collapses the list at `prepare`.
 * @param lists - Technology arrays to merge.
 */
export function mergeTechnologies(...lists: (string[] | undefined)[]): string[] {
  const seen = new Map<string, string>();
  for (const list of lists) {
    for (const raw of list ?? []) {
      const tech = typeof raw === "string" ? raw.trim() : "";
      if (!tech) continue;
      const key = tech.toLowerCase();
      if (!seen.has(key)) seen.set(key, tech);
    }
  }
  return [...seen.values()];
}

/** JSON Schema for split-commit finalize step 3/6: polished signal reasons. */
export function mergeFinalizeReasonsJsonSchema(): Record<string, unknown> {
  return {
    type: "object",
    properties: {
      signalReasons: {
        type: "object",
        properties: {
          technical: { type: "string" },
          architecture: { type: "string" },
          security: { type: "string" },
        },
        required: ["technical", "architecture", "security"],
      },
    },
    required: ["signalReasons"],
  };
}

/** JSON Schema for split-commit finalize step 4/6: composed summary. */
export function mergeFinalizeSummaryJsonSchema(): Record<string, unknown> {
  return {
    type: "object",
    properties: { summary: { type: "string" } },
    required: ["summary"],
  };
}

/** JSON Schema for split-commit finalize step 5/6: reframed commit questions. */
export function mergeFinalizeQuestionsJsonSchema(): Record<string, unknown> {
  const base = modelJsonSchema();
  const questionsAnalysis = (base.properties as Record<string, unknown>).questionsAnalysis;
  return {
    type: "object",
    properties: { questionsAnalysis },
    required: ["questionsAnalysis"],
  };
}

/** JSON Schema for `prepare`: the cleaned/deduped technology list. */
export function prepareTechnologiesJsonSchema(): Record<string, unknown> {
  return {
    type: "object",
    properties: { technologies: { type: "array", items: { type: "string" } } },
    required: ["technologies"],
  };
}

/** JSON Schema for `prepare` step 4: a flat array of reason strings. */
export function prepareReasonsJsonSchema(): Record<string, unknown> {
  return {
    type: "object",
    properties: { signalReasons: { type: "array", items: { type: "string" } } },
    required: ["signalReasons"],
  };
}

/** JSON Schema for prepare/deepen evidence card polish (batched per thread). */
export function prepareEvidenceJsonSchema(threadCount: number): Record<string, unknown> {
  return {
    type: "object",
    properties: {
      evidenceExcerpts: {
        type: "array",
        items: { type: "string" },
        minItems: threadCount,
        maxItems: threadCount,
      },
    },
    required: ["evidenceExcerpts"],
  };
}

/** JSON Schema for `prepare` step 5: role-aware questionsAnalyses + re-assessed confidence. */
export function prepareQuestionsJsonSchema(): Record<string, unknown> {
  return {
    type: "object",
    properties: {
      questionsAnalyses: aggregatedQuestionAnalysisSchema({
        allowDerivedFrom: true,
      }),
      confidence: { type: "string", enum: [...SIGNALS] },
    },
    required: ["questionsAnalyses", "confidence"],
  };
}

function migrateLineageEntrySchema(): Record<string, unknown> {
  return {
    type: "object",
    properties: {
      derivedFromThreadIds: { type: "array", items: { type: "string" } },
      derivedFromReportSignalRefs: {
        type: "array",
        items: {
          type: "object",
          properties: {
            dimension: { type: "string", enum: ["technical", "architecture", "security"] },
            index: { type: "integer", minimum: 0 },
          },
          required: ["dimension", "index"],
        },
      },
      derivedFromPreparedSignalSlots: {
        type: "array",
        items: { type: "integer", minimum: 0, maximum: 3 },
      },
    },
  };
}

/** JSON Schema for migrate LLM backfill: lineage refs only, parallel to input threads. */
export function migrateLineageJsonSchema(): Record<string, unknown> {
  return {
    type: "object",
    properties: {
      lineage: {
        type: "array",
        items: migrateLineageEntrySchema(),
      },
    },
    required: ["lineage"],
  };
}

/** JSON Schema for the report routine-gate classifier (step 1). */
export function routineCheckJsonSchema(): Record<string, unknown> {
  return {
    type: "object",
    properties: {
      routine: { type: "boolean" },
      reason: { type: "string" },
    },
    required: ["routine"],
  };
}

/** JSON Schema for the report history compaction session (text strings only). */
export function reportHistoryJsonSchema(): Record<string, unknown> {
  return {
    type: "object",
    properties: { history: { type: "array", items: { type: "string" } } },
    required: ["history"],
  };
}

/** JSON Schema for add-if-new: `{ needed, text }` only — provenance is code-side. */
export function reportNewHistoryJsonSchema(): Record<string, unknown> {
  return {
    type: "object",
    properties: {
      needed: { type: "boolean" },
      text: { type: "string" },
    },
    required: ["needed", "text"],
  };
}

/** Flattens aggregated analyses into question strings (display / Q&A order). */
export function flattenQuestions(analyses: QuestionAnalyses[]): string[] {
  return analyses.flatMap((a) => a.question);
}

/**
 * Cleans a raw per-commit `questionsAnalysis` value (from model output): trims
 * each field and drops entries that carry no `question`.
 * @param raw - The raw value.
 */
export function cleanQuestionAnalysis(raw: unknown): QuestionAnalysis[] {
  if (!Array.isArray(raw)) return [];
  return raw
    .map((q) => {
      const entry = (q ?? {}) as Partial<QuestionAnalysis>;
      return {
        observation: String(entry.observation ?? "").trim(),
        missingPiece: String(entry.missingPiece ?? "").trim(),
        question: String(entry.question ?? "").trim(),
      };
    })
    .filter((q) => q.question);
}

/**
 * Cleans a raw aggregated `questionsAnalyses` value (group/report): trims and
 * compacts each array field and drops entries that end up with no question.
 * @param raw - The raw value.
 */
const SIGNAL_DIMENSIONS = ["technical", "architecture", "security"] as const;

function cleanReportSignalReasonRefs(raw: unknown): ReportSignalReasonRef[] {
  if (!Array.isArray(raw)) return [];
  const out: ReportSignalReasonRef[] = [];
  for (const entry of raw) {
    if (!entry || typeof entry !== "object") continue;
    const dim = (entry as { dimension?: unknown }).dimension;
    const index = (entry as { index?: unknown }).index;
    if (
      typeof dim !== "string" ||
      !SIGNAL_DIMENSIONS.includes(dim as (typeof SIGNAL_DIMENSIONS)[number])
    ) {
      continue;
    }
    if (typeof index !== "number" || !Number.isInteger(index) || index < 0) continue;
    out.push({ dimension: dim as ReportSignalReasonRef["dimension"], index });
  }
  return out;
}

function cleanPreparedSignalSlots(raw: unknown): number[] {
  if (!Array.isArray(raw)) return [];
  return raw.filter(
    (slot): slot is number =>
      typeof slot === "number" && Number.isInteger(slot) && slot >= 0 && slot <= 3,
  );
}

function cleanQuestionStringArrays(): {
  strArray: (v: unknown) => string[];
  nullableStrArray: (v: unknown) => (string | null)[];
} {
  const strArray = (v: unknown): string[] =>
    Array.isArray(v) ? v.map((s) => String(s ?? "").trim()).filter(Boolean) : [];
  const nullableStrArray = (v: unknown): (string | null)[] =>
    Array.isArray(v)
      ? v.map((s) => {
          if (s === null || s === undefined) return null;
          const t = String(s).trim();
          return t || null;
        })
      : [];
  return { strArray, nullableStrArray };
}

function cleanOneQuestionAnalysis(
  raw: unknown,
  strArray: (v: unknown) => string[],
  nullableStrArray: (v: unknown) => (string | null)[],
): QuestionAnalyses | null {
  const entry = (raw ?? {}) as Partial<QuestionAnalyses>;
  const threadId =
    typeof entry.threadId === "string" && entry.threadId.trim() ? entry.threadId.trim() : undefined;
  const derivedFrom = strArray(entry.derivedFromThreadIds);
  const derivedFromReportSignalRefs = cleanReportSignalReasonRefs(
    entry.derivedFromReportSignalRefs,
  );
  const derivedFromPreparedSignalSlots = cleanPreparedSignalSlots(
    entry.derivedFromPreparedSignalSlots,
  );
  const sourceCommits = strArray(entry.sourceCommits);
  const sourceSummaries = nullableStrArray(entry.sourceSummaries);
  const sourceGroupId =
    typeof entry.sourceGroupId === "number" && Number.isFinite(entry.sourceGroupId)
      ? entry.sourceGroupId
      : undefined;
  const sourceGroupIds = Array.isArray(entry.sourceGroupIds)
    ? entry.sourceGroupIds.filter(
        (id): id is number => typeof id === "number" && Number.isFinite(id),
      )
    : [];
  const groupThreadIndex =
    typeof entry.groupThreadIndex === "number" && Number.isFinite(entry.groupThreadIndex)
      ? entry.groupThreadIndex
      : undefined;
  const threadIndex =
    typeof entry.threadIndex === "number" && Number.isFinite(entry.threadIndex)
      ? entry.threadIndex
      : undefined;
  const lineageKind =
    entry.lineageKind === "report-thread" || entry.lineageKind === "signal-reason"
      ? entry.lineageKind
      : undefined;
  const derivedFromSignalReasonIndex =
    typeof entry.derivedFromSignalReasonIndex === "number" &&
    Number.isFinite(entry.derivedFromSignalReasonIndex)
      ? entry.derivedFromSignalReasonIndex
      : undefined;
  const evidenceExcerpt =
    typeof entry.evidenceExcerpt === "string" && entry.evidenceExcerpt.trim()
      ? entry.evidenceExcerpt.trim()
      : undefined;
  const whyAsked =
    typeof entry.whyAsked === "string" && entry.whyAsked.trim() ? entry.whyAsked.trim() : undefined;
  const cleaned: QuestionAnalyses = {
    observation: strArray(entry.observation),
    missingPiece: strArray(entry.missingPiece),
    question: strArray(entry.question),
  };
  if (threadId) cleaned.threadId = threadId;
  if (sourceGroupId !== undefined) cleaned.sourceGroupId = sourceGroupId;
  if (derivedFrom.length > 0) cleaned.derivedFromThreadIds = derivedFrom;
  if (derivedFromReportSignalRefs.length > 0) {
    cleaned.derivedFromReportSignalRefs = derivedFromReportSignalRefs;
  }
  if (derivedFromPreparedSignalSlots.length > 0) {
    cleaned.derivedFromPreparedSignalSlots = derivedFromPreparedSignalSlots;
  }
  if (sourceGroupIds.length > 0) cleaned.sourceGroupIds = sourceGroupIds;
  if (sourceCommits.length > 0) cleaned.sourceCommits = sourceCommits;
  if (sourceSummaries.length > 0) cleaned.sourceSummaries = sourceSummaries;
  if (groupThreadIndex !== undefined) cleaned.groupThreadIndex = groupThreadIndex;
  if (threadIndex !== undefined) cleaned.threadIndex = threadIndex;
  if (lineageKind) cleaned.lineageKind = lineageKind;
  if (derivedFromSignalReasonIndex !== undefined) {
    cleaned.derivedFromSignalReasonIndex = derivedFromSignalReasonIndex;
  }
  if (evidenceExcerpt) cleaned.evidenceExcerpt = evidenceExcerpt;
  if (whyAsked) cleaned.whyAsked = whyAsked;
  return cleaned.question.length > 0 ? cleaned : null;
}

export function cleanQuestionAnalyses(raw: unknown): QuestionAnalyses[] {
  if (!Array.isArray(raw)) return [];
  const { strArray, nullableStrArray } = cleanQuestionStringArrays();
  return raw
    .map((q) => cleanOneQuestionAnalysis(q, strArray, nullableStrArray))
    .filter((q): q is QuestionAnalyses => q !== null);
}

/**
 * Enforces the "no signal without a reason" rule: any non-low signal whose
 * reason is empty is demoted to "low". Returns the corrected layer.
 * @param layer - The raw model output.
 */
export function enforceSignalReasons(layer: ModelLayer): ModelLayer {
  const demote = (signal: Signal, reason: string): Signal =>
    signal !== "low" && !reason.trim() ? "low" : signal;

  return {
    ...layer,
    technicalSignal: demote(layer.technicalSignal, layer.signalReasons.technical),
    architectureSignal: demote(layer.architectureSignal, layer.signalReasons.architecture),
    securitySignal: demote(layer.securitySignal, layer.signalReasons.security),
  };
}
