// SPDX-FileCopyrightText: 2026 Vasyl Zakharchenko
// SPDX-License-Identifier: Apache-2.0
//
// Generated by scripts/generate-version.ts — do not edit.

/** Encoded package semver from package.json (major·10⁶ + minor·10³ + patch). */
export const VERSION = 1000004;
