// SPDX-FileCopyrightText: 2025-2026 Vasyl Zakharchenko
// SPDX-License-Identifier: Apache-2.0

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { encodeSemver } from "../src/lib/semver-version.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8")) as {
  version: string;
};
const encoded = encodeSemver(pkg.version);

const out = `// SPDX-FileCopyrightText: 2025-2026 Vasyl Zakharchenko
// SPDX-License-Identifier: Apache-2.0
//
// Generated by scripts/generate-version.ts — do not edit.

/** Encoded package semver from package.json (major·10⁶ + minor·10³ + patch). */
export const VERSION = ${encoded};
`;

fs.writeFileSync(path.join(root, "src/lib/version.ts"), out, "utf8");
console.log(`Generated src/lib/version.ts (VERSION=${encoded} from ${pkg.version})`);
