import fs from "node:fs";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import {
  FAKE_REPO,
  sampleGitCommit,
  setupWorkgraphHome,
} from "../helpers/action-fixtures.js";
import { repoCommitsDir, setOllamaConfig, setRepoConfig } from "../../../src/lib/config.js";
import { MAX_PATCH_CHARS } from "../../../src/lib/patch-split.js";

const { getPatch, classifyMock, resolveModelMock } = vi.hoisted(() => ({
  getPatch: vi.fn(() => "commit patch"),
  classifyMock: vi.fn(),
  resolveModelMock: vi.fn(async () => "prompted-model"),
}));

vi.mock("../../../src/lib/git.js", () => ({
  resolveRepo: vi.fn((repo: string) => path.resolve(repo === "." ? FAKE_REPO : repo)),
  getCommits: vi.fn(() => [sampleGitCommit]),
  getPatch,
  getChangedFiles: vi.fn(() => [{ status: "M", path: "src/a.ts" }]),
  getChurnForPaths: vi.fn(() => ({ added: 5, deleted: 1 })),
}));

vi.mock("../../../src/lib/path-filter.js", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../../../src/lib/path-filter.js")>();
  return {
    ...actual,
    classifyPathsByFilename: (...args: unknown[]) => classifyMock(...args),
  };
});

vi.mock("../../../src/lib/select.js", () => ({
  resolveModel: (...args: unknown[]) => resolveModelMock(...args),
}));

vi.mock("../../../src/lib/ollama.js", () => ({
  resolveBaseUrl: vi.fn(() => "http://127.0.0.1:11434"),
  listModels: vi.fn(async () => [
    "narrative-model",
    "report-model",
    "commit-model",
    "test-model",
    "prompted-model",
  ]),
}));

import { evidence } from "../../../src/actions/evidence.js";

function hugeSplitPatch(sourceCount: number): string {
  const lines = ["commit abc", "Author: Dev <dev@example.com>", ""];
  for (let i = 0; i < sourceCount; i += 1) {
    const p = `src/file${i}.ts`;
    lines.push(
      `diff --git a/${p} b/${p}`,
      `--- a/${p}`,
      `+++ b/${p}`,
      `+${"x".repeat(MAX_PATCH_CHARS)}`,
    );
  }
  return lines.join("\n");
}

async function runPathFilterEvidence(model?: string): Promise<void> {
  getPatch.mockReturnValue(hugeSplitPatch(20));
  setRepoConfig(FAKE_REPO, { selectedAuthors: ["dev@example.com"] });
  classifyMock.mockImplementation(async ({ paths }: { paths: string[] }) => ({
    likelyBinary: [],
    likelyGenerated: paths.slice(10),
  }));
  await evidence({ repo: FAKE_REPO, model });
}

describe("evidence path filter", () => {
  let restoreHome: () => void;

  beforeEach(() => {
    ({ restore: restoreHome } = setupWorkgraphHome());
    process.exitCode = undefined;
    getPatch.mockReset();
    classifyMock.mockReset();
    resolveModelMock.mockClear();
  });

  afterEach(() => {
    restoreHome();
  });

  it("peels generated paths into a bucket part when initial split exceeds 15 parts", async () => {
    await runPathFilterEvidence("test-model");

    expect(classifyMock).toHaveBeenCalled();
    const dir = path.join(repoCommitsDir(FAKE_REPO), String(sampleGitCommit.timestamp));
    const manifest = JSON.parse(
      fs.readFileSync(path.join(dir, `${sampleGitCommit.hash}.json`), "utf8"),
    ) as { split: boolean; partCount: number; pathFilterApplied: boolean };

    expect(manifest.split).toBe(true);
    expect(manifest.pathFilterApplied).toBe(true);
    expect(manifest.partCount).toBe(11);

    const bucket = JSON.parse(
      fs.readFileSync(path.join(dir, `${sampleGitCommit.hash}.part11.json`), "utf8"),
    ) as { isBinaryOrAutogenerated: boolean; part: number };
    expect(bucket.isBinaryOrAutogenerated).toBe(true);
    expect(bucket.part).toBe(11);
    expect(resolveModelMock).not.toHaveBeenCalled();
  });

  it("uses saved reportModel without prompting", async () => {
    setOllamaConfig({ reportModel: "report-model", commitModel: "commit-model" });
    await runPathFilterEvidence();

    expect(resolveModelMock).not.toHaveBeenCalled();
    expect(classifyMock).toHaveBeenCalledWith(
      expect.objectContaining({ model: "report-model" }),
    );
  });

  it("prefers narrativeModel over reportModel", async () => {
    setOllamaConfig({
      narrativeModel: "narrative-model",
      reportModel: "report-model",
      commitModel: "commit-model",
    });
    await runPathFilterEvidence();

    expect(resolveModelMock).not.toHaveBeenCalled();
    expect(classifyMock).toHaveBeenCalledWith(
      expect.objectContaining({ model: "narrative-model" }),
    );
  });

  it("falls back to commitModel when narrative and report models are unset", async () => {
    setOllamaConfig({ commitModel: "commit-model" });
    await runPathFilterEvidence();

    expect(resolveModelMock).not.toHaveBeenCalled();
    expect(classifyMock).toHaveBeenCalledWith(
      expect.objectContaining({ model: "commit-model" }),
    );
  });

  it("prompts when no model is configured and does not persist the choice", async () => {
    await runPathFilterEvidence();

    expect(resolveModelMock).toHaveBeenCalled();
    expect(classifyMock).toHaveBeenCalledWith(
      expect.objectContaining({ model: "prompted-model" }),
    );
  });
});
